sudo: false
language: node_js
node_js:
  - node
before_script:
  - npm install -g grunt-cli
deploy:
  provider: npm
  email: v.klymenko@douleutaras.com
  api_key:
    secure: NJOuHzFiazpX1IGFNvQfpXenObvkC3NV0tlbfw+GQQBAkPUV0cNHcH9PUowIyBqSFKf0jBSAtZDsmTRp5QQTpWSJEcSUMuJHrxnk8RoSb4Y+iYkg8eXDC4WU2lPM5BiRVfV6uDyVK/C3uVztktUXuWu5JE9+4XFHW5xH+LmKAXDgVk7N/TRALtyG02ZJHD/Rgucj3sqN9hCwCO7+MDvDw9IpxLJH4BHVRlsDTfDDf0LUQhsqcsE8x+X25pdg5TuM6k5p08lSu/0ecD/Ywcx/i/CdOofwKRLc++vfgddgsdkHH7FFLzntmOR2rKJlZYLQ/sIad7O6qi65DsA7ajs8Ixekt7utFL5O5HWzVpwOMsMm4peybVh6YJOFT3haZ5K4KO+/ri3kHcbR1He+dfg3chAvlGP5pl50qB7FHdV8mFXBUtDjRReOJRKk4h9vkR8XmyG8DW50IAhwDp3kwilZ/zleJqQdM9ZMio5QvoD7PgfL8QZaiici36dG7zspUXik6Pw9NWRUCjCzEDTvSvmTiVJgoXHfFpVXw9QWHEnyar+o2LY7tiQFBHVYjnze7l71cL3MYqMMPBtxzCqEaxbp+jeSKo9Io4HQsODs/NL+eQg7qi8EkH5x3nf9NOwFQFKuh8ZWJKj2vUKk7Ai1pHBUlrzfbaw149oFPhZ3sUD1/8U=
  on:
    tags: true
    repo: douleutaras/angular-gettext-tools